# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "usbhid"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c636c2b5-5b02-4ebb-9e45-b6ae9454501a";
    fsType = "btrfs";
    options = [ "subvol=root,compress=zstd" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/c636c2b5-5b02-4ebb-9e45-b6ae9454501a";
    fsType = "btrfs";
    options = [ "subvol=home,compress=zstd" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/c636c2b5-5b02-4ebb-9e45-b6ae9454501a";
    fsType = "btrfs";
    options = [ "subvol=nix,compress=zstd,noatime" ];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/c636c2b5-5b02-4ebb-9e45-b6ae9454501a";
    fsType = "btrfs";
    options = [ "subvol=swap,noatime" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4FCD-D30E";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/mnt/nvme0n1p4" = {
    device = "/dev/disk/by-uuid/C608833408832293";
    fsType = "ntfs3";
    options = [
      "rw"
      "uid=1000"
      "gid=100"
      "nofail"
    ];
  };

  swapDevices = [
    {
      device = "/swap/swapfile";
      size = 8 * 1024;
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
